//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.17929
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZchMatome.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZchMatome.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelDetailPage_NotificationToggleSwitchHeader {
            get {
                return ResourceManager.GetString("ChannelDetailPage_NotificationToggleSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelDetailPage_OfficialBlog {
            get {
                return ResourceManager.GetString("ChannelDetailPage_OfficialBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BLOG INFORMATION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelDetailPage_PageHeaderTitle {
            get {
                return ResourceManager.GetString("ChannelDetailPage_PageHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelDetailPage_PivotItem_ChannelSettings {
            get {
                return ResourceManager.GetString("ChannelDetailPage_PivotItem_ChannelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   what&apos;s new に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelDetailPage_PivotItem_ChannelUpdates {
            get {
                return ResourceManager.GetString("ChannelDetailPage_PivotItem_ChannelUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subscription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChannelDetailPage_SubscriptionToggleSwitchHeader {
            get {
                return ResourceManager.GetString("ChannelDetailPage_SubscriptionToggleSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AppBar_IconButtonText_Cancel {
            get {
                return ResourceManager.GetString("Common_AppBar_IconButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AppBar_IconButtonText_Complete {
            get {
                return ResourceManager.GetString("Common_AppBar_IconButtonText_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AppBar_MenuItemText_Refresh {
            get {
                return ResourceManager.GetString("Common_AppBar_MenuItemText_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete all favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_AppBar_MenuItemText_TruncateFavorites {
            get {
                return ResourceManager.GetString("Common_AppBar_MenuItemText_TruncateFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just a moment... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ToggleSwitch_Content_Off {
            get {
                return ResourceManager.GetString("Common_ToggleSwitch_Content_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ToggleSwitch_Content_On {
            get {
                return ResourceManager.GetString("Common_ToggleSwitch_Content_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   blue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Blue {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   brown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Brown {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   green に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Green {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Lime {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   magenta に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Magenta {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mango に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Mango {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Mango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_None {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pink に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Pink {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   purple に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Purple {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   red に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Red {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   teal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Constants_Media_AccentColors_Teal {
            get {
                return ResourceManager.GetString("Constants_Media_AccentColors_Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   blogs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupAndChannelListPage_ChannelList_Title {
            get {
                return ResourceManager.GetString("GroupAndChannelListPage_ChannelList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   groups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupAndChannelListPage_GroupList_Title {
            get {
                return ResourceManager.GetString("GroupAndChannelListPage_GroupList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BLOG INFORMATION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupAndChannelListPage_PageHeaderTitle {
            get {
                return ResourceManager.GetString("GroupAndChannelListPage_PageHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CATEGORY INFORMATION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupDetailPage_PageHeaderTitle {
            get {
                return ResourceManager.GetString("GroupDetailPage_PageHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   category settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupDetailPage_PageTitle {
            get {
                return ResourceManager.GetString("GroupDetailPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subscribe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupDetailPage_SubscribeToggleSwitchHeader {
            get {
                return ResourceManager.GetString("GroupDetailPage_SubscribeToggleSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_AppBar_MenuItemText_AboutTheApplication {
            get {
                return ResourceManager.GetString("MainPage_AppBar_MenuItemText_AboutTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   blog information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_AppBar_MenuItemText_GroupAndChannelInformation {
            get {
                return ResourceManager.GetString("MainPage_AppBar_MenuItemText_GroupAndChannelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t retrieve data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_Error_FailedToGetAllFeedGroups {
            get {
                return ResourceManager.GetString("MainPage_Error_FailedToGetAllFeedGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t retrieve data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_Error_FailedToGetAllFeedGroupsAndChannels {
            get {
                return ResourceManager.GetString("MainPage_Error_FailedToGetAllFeedGroupsAndChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t retrieve data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_Error_FailedToGetFeedItems {
            get {
                return ResourceManager.GetString("MainPage_Error_FailedToGetFeedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2ch matome reader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_PageHeaderTitle {
            get {
                return ResourceManager.GetString("MainPage_PageHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   what&apos;s new に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_PivotItem_ChannelUpdates {
            get {
                return ResourceManager.GetString("MainPage_PivotItem_ChannelUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   favorites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_PivotItem_Favorites {
            get {
                return ResourceManager.GetString("MainPage_PivotItem_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no favorites.
        ///Tap on ☆ on each article
        ///to mark as favorite. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_TipsForNoFavorites {
            get {
                return ResourceManager.GetString("MainPage_TipsForNoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no subscriptions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPage_TipsForNoSubscription {
            get {
                return ResourceManager.GetString("MainPage_TipsForNoSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details and reviews for app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_ApplicationDetailsAndReviews {
            get {
                return ResourceManager.GetString("PreferencesPage_ApplicationDetailsAndReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2ch matome reader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_ApplicationTitle {
            get {
                return ResourceManager.GetString("PreferencesPage_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_ApplicationVersion {
            get {
                return ResourceManager.GetString("PreferencesPage_ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just a moment... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Busy {
            get {
                return ResourceManager.GetString("PreferencesPage_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration failed. Check your network connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Error_NotificationRegistrationFailed {
            get {
                return ResourceManager.GetString("PreferencesPage_Error_NotificationRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open app details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_GotoApplicationDetails {
            get {
                return ResourceManager.GetString("PreferencesPage_GotoApplicationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Push notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Notification_ReceiveNotification {
            get {
                return ResourceManager.GetString("PreferencesPage_Notification_ReceiveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation of push notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Notification_ReceiveNotification_ConfirmationCaption {
            get {
                return ResourceManager.GetString("PreferencesPage_Notification_ReceiveNotification_ConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabling push notification, you can receive tile and toast notification for blog updates. You can turn this functionality off anytime. Do you want to enable this functionality? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Notification_ReceiveNotification_ConfirmationText {
            get {
                return ResourceManager.GetString("PreferencesPage_Notification_ReceiveNotification_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can receive tile notification for blog updates you subscribe. You can also receive toast notification for blog updates you wants. Pin this app to your start screen to receive tile notification. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_Notification_ReceiveNotificationDesc {
            get {
                return ResourceManager.GetString("PreferencesPage_Notification_ReceiveNotificationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETTINGS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_PageHeaderTitle {
            get {
                return ResourceManager.GetString("PreferencesPage_PageHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   about app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_PivotItem_AboutTheApplication {
            get {
                return ResourceManager.GetString("PreferencesPage_PivotItem_AboutTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_PivotItem_Notification {
            get {
                return ResourceManager.GetString("PreferencesPage_PivotItem_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_TwitterAccountForSupport {
            get {
                return ResourceManager.GetString("PreferencesPage_TwitterAccountForSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @yamac_support に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PreferencesPage_TwitterAccountForSupportValue {
            get {
                return ResourceManager.GetString("PreferencesPage_TwitterAccountForSupportValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string String1PreferencesPage_Notification_ReceiveNotification {
            get {
                return ResourceManager.GetString("String1PreferencesPage_Notification_ReceiveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   open with browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebPage_AppBar_MenuItemText_OpenWithBrowser {
            get {
                return ResourceManager.GetString("WebPage_AppBar_MenuItemText_OpenWithBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   share page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebPage_AppBar_MenuItemText_ShareThePage {
            get {
                return ResourceManager.GetString("WebPage_AppBar_MenuItemText_ShareThePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check your cellular data or Wi-Fi connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebPage_Error_NavigationFailedMessage {
            get {
                return ResourceManager.GetString("WebPage_Error_NavigationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The page cannot be displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebPage_Error_NavigationFailedTitle {
            get {
                return ResourceManager.GetString("WebPage_Error_NavigationFailedTitle", resourceCulture);
            }
        }
    }
}
